# Data Gathering

In [1]:
import os 
os.chdir('D:/Data_sets/')

In [2]:
import pandas as pd
df=pd.read_csv('Cars93.csv')
df

id Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0    1        Acura  Integra    Small       12.9   15.9       18.8        25   
1    2        Acura   Legend  Midsize       29.2   33.9       38.7        18   
2    3         Audi       90  Compact       25.9   29.1       32.3        20   
3    4         Audi      100  Midsize       30.8   37.7       44.6        19   
4    5          BMW     535i  Midsize       23.7   30.0       36.2        22   
..  ..          ...      ...      ...        ...    ...        ...       ...   
88  89   Volkswagen  Eurovan      Van       16.6   19.7       22.7        17   
89  90   Volkswagen   Passat  Compact       17.6   20.0       22.4        21   
90  91   Volkswagen  Corrado   Sporty       22.9   23.3       23.7        18   
91  92        Volvo      240  Compact       21.8   22.7       23.5        21   
92  93        Volvo      850  Midsize       24.8   26.7       28.5        20   

    MPG.highway             AirBags  ... Passengers Length  Wheelbase  Width  \
0            31                 NaN  ...          5    177        102     68   
1            25  Driver & Passenger  ...          5    195        115     71   
2            26         Driver only  ...          5    180        102     67   
3            26                 NaN  ...          6    193        106     70   
4            30         Driver only  ...          4    186        109     69   
..          ...                 ...  ...        ...    ...        ...    ...   
88           21                 NaN  ...          7    187        115     72   
89           30                 NaN  ...          5    180        103     67   
90           25                 NaN  ...          4    159         97     66   
91           28         Driver only  ...          5    190        104     67   
92           28  Driver & Passenger  ...          5    184        105     69   

    Turn.circle  Rear.seat.room Luggage.room  Weight   Origin  \
0            37            26.5         11.0    2705  non-USA   
1            38            30.0         15.0    3560  non-USA   
2            37            28.0         14.0    3375  non-USA   
3            37            31.0         17.0    3405  non-USA   
4            39            27.0         13.0    3640  non-USA   
..          ...             ...          ...     ...      ...   
88           38            34.0          NaN    3960  non-USA   
89           35            31.5         14.0    2985  non-USA   
90           36            26.0         15.0    2810  non-USA   
91           37            29.5         14.0    2985  non-USA   
92           38            30.0         15.0    3245  non-USA   

                  Make  
0        Acura Integra  
1         Acura Legend  
2              Audi 90  
3             Audi 100  
4             BMW 535i  
..                 ...  
88  Volkswagen Eurovan  
89   Volkswagen Passat  
90  Volkswagen Corrado  
91           Volvo 240  
92           Volvo 850  

[93 rows x 28 columns]

# EDA

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  93 non-null     int64  
 1   Manufacturer        93 non-null     object 
 2   Model               93 non-null     object 
 3   Type                93 non-null     object 
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64  
 8   MPG.highway         93 non-null     int64  
 9   AirBags             56 non-null     object 
 10  DriveTrain          93 non-null     object 
 11  Cylinders           93 non-null     object 
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64  
 14  RPM                 93 non-null     int64  
 15  Rev.per.mile        93 non-null     int64  
 16  Man.trans.

In [4]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

# Classification

### Defining x and y

In [5]:
x=df.drop(['Man.trans.avail'],axis=1)
y=df['Man.trans.avail']

# Preprocessing

In [6]:
from preprocessor import Preprocess

In [7]:
x1=Preprocess(x)
x1

Num_pipe__id  Num_pipe__Min.Price  Num_pipe__Price  Num_pipe__Max.Price  \
0       0.000000             0.160207         0.155963             0.151179   
1       0.010870             0.581395         0.486239             0.427184   
2       0.021739             0.496124         0.398165             0.338419   
3       0.032609             0.622739         0.555963             0.509015   
4       0.043478             0.439276         0.414679             0.392510   
..           ...                  ...              ...                  ...   
88      0.956522             0.255814         0.225688             0.205270   
89      0.967391             0.281654         0.231193             0.201110   
90      0.978261             0.418605         0.291743             0.219140   
91      0.989130             0.390181         0.280734             0.216366   
92      1.000000             0.467700         0.354128             0.285714   

    Num_pipe__MPG.city  Num_pipe__MPG.highway  Num_pipe__EngineSize  \
0             0.322581               0.366667              0.170213   
1             0.096774               0.166667              0.468085   
2             0.161290               0.200000              0.382979   
3             0.129032               0.200000              0.382979   
4             0.225806               0.333333              0.531915   
..                 ...                    ...                   ...   
88            0.064516               0.033333              0.319149   
89            0.193548               0.333333              0.212766   
90            0.096774               0.166667              0.382979   
91            0.193548               0.266667              0.276596   
92            0.161290               0.266667              0.297872   

    Num_pipe__Horsepower  Num_pipe__RPM  Num_pipe__Rev.per.mile  ...  \
0               0.346939       0.925926                0.644764  ...   
1               0.591837       0.629630                0.416838  ...   
2               0.477551       0.629630                0.394251  ...   
3               0.477551       0.629630                0.498973  ...   
4               0.624490       0.703704                0.503080  ...   
..                   ...            ...                     ...  ...   
88              0.220408       0.259259                0.655031  ...   
89              0.322449       0.740741                0.560575  ...   
90              0.502041       0.740741                0.437372  ...   
91              0.240816       0.592593                0.367556  ...   
92              0.461224       0.888889                0.406571  ...   

    cat_pipe__Make_Toyota Camry  cat_pipe__Make_Toyota Celica  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   
..                          ...                           ...   
88                          0.0                           0.0   
89                          0.0                           0.0   
90                          0.0                           0.0   
91                          0.0                           0.0   
92                          0.0                           0.0   

    cat_pipe__Make_Toyota Previa  cat_pipe__Make_Toyota Tercel  \
0                            0.0                           0.0   
1                            0.0                           0.0   
2                            0.0                           0.0   
3                            0.0                           0.0   
4                            0.0                           0.0   
..                           ...                           ...   
88                           0.0                           0.0   
89                          

# Train test split

In [8]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.2,random_state=23)

# Model

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
rf=RandomForestClassifier()

In [11]:
rf.fit(x_train,y_train)

RandomForestClassifier()

# Train Data evalution

In [12]:
from Classification_evaluate import Classification_evaluate

In [13]:
y_pred_train=rf.predict(x_train)

In [14]:
y_pred_train

array(['No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
       'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'Yes', 'Yes', 'Yes', 'Yes', 'Yes'], dtype=object)

In [15]:
Classification_evaluate(y_pred_train,y_train)

********************************************************************************
Accuracy: 1.0
____________________________________________________________________________________________________
Classification Report:
               precision    recall  f1-score   support

          No       1.00      1.00      1.00        23
         Yes       1.00      1.00      1.00        51

    accuracy                           1.00        74
   macro avg       1.00      1.00      1.00        74
weighted avg       1.00      1.00      1.00        74

____________________________________________________________________________________________________
Confusion Matrix:
 [[23  0]
 [ 0 51]]
********************************************************************************


# Test data evalution

In [16]:
y_pred_test=rf.predict(x_test)

In [17]:
y_pred_test

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No'],
      dtype=object)

In [18]:
Classification_evaluate(y_pred_test,y_test)

********************************************************************************
Accuracy: 0.8947368421052632
____________________________________________________________________________________________________
Classification Report:
               precision    recall  f1-score   support

          No       0.89      0.89      0.89         9
         Yes       0.90      0.90      0.90        10

    accuracy                           0.89        19
   macro avg       0.89      0.89      0.89        19
weighted avg       0.89      0.89      0.89        19

____________________________________________________________________________________________________
Confusion Matrix:
 [[8 1]
 [1 9]]
********************************************************************************


# Hyperparameter tunningg

In [19]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [24]:
grid={
    'n_estimators':range(1,250),
    'criterion':['gini','entropy'],
    'max_depth':range(1,200),
    'min_samples_split':range(1,20),
    'min_samples_leaf':range(1,20),
    'max_samples':np.arange(0,1,0.1)
}

In [25]:
rs=RandomizedSearchCV(rf,param_distributions=grid,cv=2)
rs.fit(x_train,y_train)

RandomizedSearchCV(cv=2, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': range(1, 200),
                                        'max_samples': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
                                        'min_samples_leaf': range(1, 20),
                                        'min_samples_split': range(1, 20),
                                        'n_estimators': range(1, 250)})

In [26]:
rs.best_params_

{'n_estimators': 108,
 'min_samples_split': 4,
 'min_samples_leaf': 1,
 'max_samples': 0.2,
 'max_depth': 93,
 'criterion': 'entropy'}

In [27]:
rf1=rs.best_estimator_
rf1

RandomForestClassifier(criterion='entropy', max_depth=93, max_samples=0.2,
                       min_samples_split=4, n_estimators=108)

# Evaluation After Tuning

In [28]:
y_pred_train=rf1.predict(x_train)

Classification_evaluate(y_pred_train,y_train)

********************************************************************************
Accuracy: 0.918918918918919
____________________________________________________________________________________________________
Classification Report:
               precision    recall  f1-score   support

          No       0.87      0.87      0.87        23
         Yes       0.94      0.94      0.94        51

    accuracy                           0.92        74
   macro avg       0.91      0.91      0.91        74
weighted avg       0.92      0.92      0.92        74

____________________________________________________________________________________________________
Confusion Matrix:
 [[20  3]
 [ 3 48]]
********************************************************************************


In [29]:
y_pred_test=rf1.predict(x_test)

Classification_evaluate(y_pred_test,y_test)

********************************************************************************
Accuracy: 0.8947368421052632
____________________________________________________________________________________________________
Classification Report:
               precision    recall  f1-score   support

          No       0.78      1.00      0.88         7
         Yes       1.00      0.83      0.91        12

    accuracy                           0.89        19
   macro avg       0.89      0.92      0.89        19
weighted avg       0.92      0.89      0.90        19

____________________________________________________________________________________________________
Confusion Matrix:
 [[ 7  0]
 [ 2 10]]
********************************************************************************


# Regression

### define x and y for Regression

In [30]:
x=df.drop(['Price'],axis=1)
y=df['Price']

## Preprocessing

In [32]:
x1=Preprocess(x) 
x1

Num_pipe__id  Num_pipe__Min.Price  Num_pipe__Max.Price  \
0       0.000000             0.160207             0.151179   
1       0.010870             0.581395             0.427184   
2       0.021739             0.496124             0.338419   
3       0.032609             0.622739             0.509015   
4       0.043478             0.439276             0.392510   
..           ...                  ...                  ...   
88      0.956522             0.255814             0.205270   
89      0.967391             0.281654             0.201110   
90      0.978261             0.418605             0.219140   
91      0.989130             0.390181             0.216366   
92      1.000000             0.467700             0.285714   

    Num_pipe__MPG.city  Num_pipe__MPG.highway  Num_pipe__EngineSize  \
0             0.322581               0.366667              0.170213   
1             0.096774               0.166667              0.468085   
2             0.161290               0.200000              0.382979   
3             0.129032               0.200000              0.382979   
4             0.225806               0.333333              0.531915   
..                 ...                    ...                   ...   
88            0.064516               0.033333              0.319149   
89            0.193548               0.333333              0.212766   
90            0.096774               0.166667              0.382979   
91            0.193548               0.266667              0.276596   
92            0.161290               0.266667              0.297872   

    Num_pipe__Horsepower  Num_pipe__RPM  Num_pipe__Rev.per.mile  \
0               0.346939       0.925926                0.644764   
1               0.591837       0.629630                0.416838   
2               0.477551       0.629630                0.394251   
3               0.477551       0.629630                0.498973   
4               0.624490       0.703704                0.503080   
..                   ...            ...                     ...   
88              0.220408       0.259259                0.655031   
89              0.322449       0.740741                0.560575   
90              0.502041       0.740741                0.437372   
91              0.240816       0.592593                0.367556   
92              0.461224       0.888889                0.406571   

    Num_pipe__Fuel.tank.capacity  ...  cat_pipe__Make_Toyota Camry  \
0                       0.224719  ...                          0.0   
1                       0.494382  ...                          0.0   
2                       0.432584  ...                          0.0   
3                       0.668539  ...                          0.0   
4                       0.668539  ...                          0.0   
..                           ...  ...                          ...   
88                      0.668539  ...                          0.0   
89                      0.522472  ...                          0.0   
90                      0.522472  ...                          0.0   
91                      0.370787  ...                          0.0   
92                      0.567416  ...                          0.0   

    cat_pipe__Make_Toyota Celica  cat_pipe__Make_Toyota Previa  \
0                            0.0                           0.0   
1                            0.0                           0.0   
2                            0.0                           0.0   
3                            0.0                           0.0   
4                            0.0                           0.0   
..                           ...                           ...   
88                           0.0                           0.0   
89                           0.0                           0.0   
90                           0.0                           0.0   
91                           0.0                           0.0   
92                           0.0  

## Train Test Split

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.2,random_state=23)

## Random Forest Model for Regression

In [34]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(random_state=34)
rf.fit(x_train,y_train)

RandomForestRegressor(random_state=34)

## Training Data Evaluation

In [36]:
from evalute import Regression_evaluate
y_pred_train=rf.predict(x_train)

Regression_evaluate(y_pred_train,y_train)

**************************************************
MSE: 0.453
MAE: 0.453
RMSE: 0.673
R2 SCore: 0.983
**************************************************


## Testing Data Evaluation

In [37]:
y_pred_test=rf.predict(x_test)

Regression_evaluate(y_pred_test,y_test)

**************************************************
MSE: 1.302
MAE: 1.302
RMSE: 1.141
R2 SCore: 0.925
**************************************************


## *Hyperparameter Tuning*

In [38]:
grid={
    'n_estimators':range(1,250),
    'max_depth':range(1,200),
    'min_samples_split':range(1,20),
    'min_samples_leaf':range(1,20),
    'max_samples':np.arange(0,1,0.1)
}

In [39]:
rs=RandomizedSearchCV(rf,param_distributions=grid,cv=3)
rs.fit(x_train,y_train)

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(random_state=34),
                   param_distributions={'max_depth': range(1, 200),
                                        'max_samples': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
                                        'min_samples_leaf': range(1, 20),
                                        'min_samples_split': range(1, 20),
                                        'n_estimators': range(1, 250)})

In [40]:
rs.best_params_

{'n_estimators': 132,
 'min_samples_split': 5,
 'min_samples_leaf': 5,
 'max_samples': 0.8,
 'max_depth': 150}

In [41]:
rf1=rs.best_estimator_
rf1

RandomForestRegressor(max_depth=150, max_samples=0.8, min_samples_leaf=5,
                      min_samples_split=5, n_estimators=132, random_state=34)

In [42]:
y_pred_train=rf1.predict(x_train)

Regression_evaluate(y_pred_train,y_train)

**************************************************
MSE: 1.093
MAE: 1.093
RMSE: 1.045
R2 SCore: 0.851
**************************************************


In [43]:
y_pred_test=rf1.predict(x_test)

Regression_evaluate(y_pred_test,y_test)

**************************************************
MSE: 1.359
MAE: 1.359
RMSE: 1.166
R2 SCore: 0.885
**************************************************


In [44]:
x_test.shape

(19, 257)

## Feature Importance

In [45]:
imp=rf1.feature_importances_
imp

array([8.23777785e-06, 2.84973517e-01, 6.55774972e-01, 1.31380911e-04,
       3.11231741e-04, 3.41387210e-04, 4.67387155e-03, 1.54551407e-05,
       1.35997000e-04, 1.66691660e-04, 4.92943846e-05, 1.08652964e-03,
       4.91573552e-05, 2.83963064e-03, 1.99891507e-04, 5.02899271e-04,
       1.16449608e-04, 4.86234051e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [46]:
np.cumsum(imp)

array([8.23777785e-06, 2.84981755e-01, 9.40756727e-01, 9.40888108e-01,
       9.41199340e-01, 9.41540727e-01, 9.46214599e-01, 9.46230054e-01,
       9.46366051e-01, 9.46532743e-01, 9.46582037e-01, 9.47668567e-01,
       9.47717724e-01, 9.50557355e-01, 9.50757246e-01, 9.51260145e-01,
       9.51376595e-01, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
      

In [47]:
Imp1=pd.DataFrame(x_train.columns,columns=['Feature'])
Imp1

Feature
0                         Num_pipe__id
1                  Num_pipe__Min.Price
2                  Num_pipe__Max.Price
3                   Num_pipe__MPG.city
4                Num_pipe__MPG.highway
..                                 ...
252  cat_pipe__Make_Volkswagen Eurovan
253      cat_pipe__Make_Volkswagen Fox
254   cat_pipe__Make_Volkswagen Passat
255           cat_pipe__Make_Volvo 240
256           cat_pipe__Make_Volvo 850

[257 rows x 1 columns]

In [48]:
Imp1['Importance']=imp
Imp1

Feature  Importance
0                         Num_pipe__id    0.000008
1                  Num_pipe__Min.Price    0.284974
2                  Num_pipe__Max.Price    0.655775
3                   Num_pipe__MPG.city    0.000131
4                Num_pipe__MPG.highway    0.000311
..                                 ...         ...
252  cat_pipe__Make_Volkswagen Eurovan    0.000000
253      cat_pipe__Make_Volkswagen Fox    0.000000
254   cat_pipe__Make_Volkswagen Passat    0.000000
255           cat_pipe__Make_Volvo 240    0.000000
256           cat_pipe__Make_Volvo 850    0.000000

[257 rows x 2 columns]